version: '3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80" 
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: hogehoge
    depends_on:
      - db
    volumes:
      - ./theme:/var/www/html/wp-content/themes/cross2019

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER : wp_user
      MYSQL_PASSWORD: hogehoge
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

